language: python
python:
  - "3.7"
install:
  - pip install markdown2
  - pip wheel . -w dist
script:
  - cd dist
  - find . -type f -printf '[%P](%p)  \n' >index.md
  - python -m markdown2 index.md >index.html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master

